#开发配置

spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.3.61
    port: 6379
    database: 0

#mybatis配置
mybatis:
  typeAliasesPackage: com.yuanju.demo.po
  mapperLocations: classpath:mapper/*.xml


server:
  port: 8080


swagger:
  basePackage: com.yuanju.demo
  title: 用户服务
  description: 用户基本增删改查
  version: V1.0

